version: '3'
services:
  nginx:
    image: nginx:latest
    depends_on:
      - php
    volumes:
      - ./app/public:/var/www/public
      - ./docker/nginx/config:/etc/nginx
    ports:
      - "80:80"
  php:
    image: aldump/bom_php
    volumes:
      - ./app:/var/www
    working_dir: /var/www